### ISSUE TITLE
Lost ability to export without base?

### ISSUE THREAD

**Issue by SleepyBandit** [christofsteel/herosaver#12]
I just noticed a new push was made and now I cannot export without the base. That was by far one of the best features. I hate Heroforge bases and it leaves no room to be able to better scale the model.

Why was this functionality removed????

**Comment by christofsteel** [comment]
Hi,
HeroForge changed their internal API, and I needed to adapt the saver to that. Unfortunately my previous attempt to export the miniature without the base does not work anymore :(.
I don't think I need to change much to adapt to their new API, but right now it is unfortunately broken.

**Comment by TeaWithLucas** [comment]
You can remove the base in the program, just click the base that's selected to clear it.

**Comment by SleepyBandit** [comment]
> You can remove the base in the program, just click the base that's selected to clear it.

You're right! Is that a new feature? I never noticed! This solves the problem. thanks.
