### ISSUE TITLE
Facial Expressions do not appear.

### ISSUE THREAD

**Issue by Sorrowsinme** [christofsteel/herosaver#13]
Hi, First of all let me say that I love the work you have done.
If it were possible I wouldn't mind paying for your awesome contribution to the 3D printing community. Thank you, really.

I know a thread about facial expressions was open and closed already, but I'm having some troubles exporting the STL with the expressions.
I have a lizardmen I'm trying to get, as soon as I try to export the file in the Console (using Opera Browser) the expression on the stl file is neutral and the teeth go missing, is this normal? am I doing something wrong?

Once again thank you for this project.
Because of our country's law, getting packages from certain countries is just pratically impossible without paying a great sum of money to get it clear from customs.
Really, thank you.

**Comment by christofsteel** [comment]
Hi, I am sorry to say, but I discontinued the project. I absolutely do not want to get paid for this project. Regarding your problem to get packages shipped to your country, maybe you can buy the stl files from HeroForge (If money transfer is not prevented).

If your lizardmen are creatures from the D&D Monster Manual, (this guy)[https://www.shapeways.com/shops/dmworkshop] modeled basically every creature in it, and you can download them for free.
