### ISSUE TITLE
Not working Anymore

### ISSUE THREAD

**Issue by Jcake72** [christofsteel/herosaver#3]
Seems the website has changed and is no longer working

**Comment by christofsteel** [comment]
Ugh, you are right. Until I adapt the script for the new design, the README contains a workaround for the new website.

**Comment by christofsteel** [comment]
Yes. At the moment the UI code is broken, so no buttons appear, but you can trigger the export via `stl.click()` (for the figure without base) or `stl_base.click()` (for the figure with base). But fear not, I have adapted the code to work with the new website. It just needs a bit polish, I think I will release it tomorrow or the day after, depending on how much time I have ;)

**Comment by christofsteel** [comment]
Hi,
the script should again work with the new HeroForge UI. Additionally you only need to paste one line. Everything else will be injected by the script :)
