### ISSUE TITLE
Morphs does not seem to be applied

### ISSUE THREAD

**Issue by SimplyLinn** [christofsteel/herosaver#5]
https://github.com/christofsteel/herosaver/blob/e1f57e260d69c2e4283106cbcc3fb74b47183989/herosaver.js#L137-L142

I've been looking at the code trying to figure out why facial expressions are not applied. Apparently you calculate the morph vectors, but never use them on the final exported mesh. The linked line shows where the last morph calculation is done, and that variable is never used after calculation is done.

**Comment by christofsteel** [comment]
Huh, you are absolutely right... I will look into this, when I have the time

**Comment by jesuswu** [comment]
Is this still planned to be fixed? or maybe branch an older version with working morphs would be useful too.

**Comment by SleepyBandit** [comment]
Using [other versions](https://gist.github.com/jcarletto27/e271bbb7639c4bed2427) of the original code you built this off of, it appears that there are two problems. The first is you're missing a key bit of code where morphVector is used to set tempVector to apply the morphs. This was provided in the version I linked to above.

Starting at [line 146](https://github.com/christofsteel/herosaver/blob/e1f57e260d69c2e4283106cbcc3fb74b47183989/herosaver.js#L146), the for loop should look like the following
`
for (var k = 0; k < 4; k++) {
	if (mesh.geometry.morphTargets !== 'undefined') {
		var tempVector = new THREE.Vector4(morphVector.x, morphVector.y, morphVector.z);
	} else {
		var tempVector = new THREE.Vector4(vector.x, vector.y, vector.z);
	}
	tempVector.multiplyScalar(weights[k]);
	//the inverse takes the vector into local bone space
	//which is then transformed to the appropriate world space
	tempVector.applyMatrix4(inverses[k])
	.applyMatrix4(skinMatrices[k]);
	finalVector.add(tempVector);

}
`
While this will apply the morphs, it leads to the second issue where the morph vectors do not appear to apply correctly. It looks like the vertices are lost at some point for the morphs.

I have almost zero knowledge of threeJS but from some testing I believe the issue occurs in the if statement at [line 33 ](https://github.com/christofsteel/herosaver/blob/e1f57e260d69c2e4283106cbcc3fb74b47183989/herosaver.js#L33) when you work to transform the BufferGeometry object into a standard Geometry object. Something is causing the morphs to lose positioning information during this transformation.

Just some input to hopefully help. It would be really great if this got fixed.

**Comment by Unikatze** [comment]
Was there ever any progress on this? 
I love the current state, because really, who can see a smile at 30mm, but still would be cool to have.

**Comment by christofsteel** [comment]
I think I am quiet close. Looking at
 
https://github.com/christofsteel/herosaver/blob/e1f57e260d69c2e4283106cbcc3fb74b47183989/herosaver.js#L38

I am certain, this is a typo and there should not be a zero. Unfortunately fixing that opens up problems at other places. I am working on it ;)

**Comment by christofsteel** [comment]
Or not... this is not a typo... damnit

**Comment by christofsteel** [comment]
ok, it seems, that cloning the geometry does not preserve the morphs

https://github.com/christofsteel/herosaver/blob/e1f57e260d69c2e4283106cbcc3fb74b47183989/herosaver.js#L34

**Comment by Unikatze** [comment]
I don't really understand much about what you just said XD
