### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by miki-debicki** [christofsteel/herosaver#7]
First of all, amazing work! However, when I open up downloaded stl project it is scaled down 10 times, is it a common issue?

**Comment by christofsteel** [comment]
Thank you, but it is mostly copy pasted from other sources. 
Yes, this is an issue. I tried implementing a scaling in the javascript, but ended up confusing myself ;) So I just accepted it and scale the miniatures in my 3d printing software.

**Comment by SleepyBandit** [comment]
This is still an issue even though latest accepted pull request said it was fixed.

**Comment by christofsteel** [comment]
The last accepted pull request was #9 this added a more robust naming scheme to the output stl file

**Comment by TeaWithLucas** [comment]
That pull wasn't implemented, my implementation is crude, but works, and I'll probably make a fork with it for people to use alongside myself.

**Comment by christofsteel** [comment]
Yes. Since you can rotate and scale in basically every slicer, this is not very high on my priority list ;)
