### ISSUE TITLE
 problems downloading

### ISSUE THREAD

**Issue by saidzareh** [christofsteel/herosaver#8]
the code no longer works

this message appears when I try to download

VM64:1 Uncaught TypeError: Cannot read property 'threeObj' of undefined
    at HTMLAnchorElement.<anonymous> (<anonymous>:1:8716)
    at HTMLAnchorElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLAnchorElement.y.handle (jquery-3.3.1.min.js:2)

you have how to arrange?

**Comment by saidzareh** [comment]
first of all, thanks for everything

**Comment by christofsteel** [comment]
HeroForge changed their internal API. Previously they used the variable `CK.activeCharacter` to store all the information of the model. It seems they have changed that. I am tracking down the right variable, so it should work soon.

**Comment by christofsteel** [comment]
Ok. Unfortunately the option to just export the figure (without the base) had to be dropped (I need to investigate further to solve that), but exporting per se works again.
